version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=evaluser
      - POSTGRES_PASSWORD=evalpass
      - POSTGRES_DB=evaluation
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  worker:
    build: .
    command: celery -A celery_app worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - DATABASE_URL=postgresql://evaluser:evalpass@db:5432/evaluation
    depends_on:
      - rabbitmq
      - db

  tester:
    build: .
    command: python test_end_to_end.py
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://evaluser:evalpass@db:5432/evaluation
    depends_on:
      - rabbitmq
      - worker
      - db

volumes:
  postgres_data:
